/* qwen_chat_gate -- the Qwen3.8-Flash-Next tokenizer, renderer, span map and
 * output parser graded against HF (L251 S5).  Model-free; seconds.
 *
 * Goldens: tests/test-vectors/qwen38/, generated by tests/qwen/gen_qwen_goldens.py
 * from transformers' apply_chat_template and tokenizers' Tokenizer (meta.json
 * records the versions and the input hashes).
 *
 *   T1 adversarial strings        encode(text) == HF ids
 *   T2 span guard                 encode(text, client spans) == tokenizers' components with
 *                                 added tokens cut only outside the spans
 *   T3 every scalar value         per-4096-codepoint chunk: count + sha1(ids) == HF
 *   T4 calibration corpus         the 466 HF-rendered rows: count + sha1(ids) == HF   (--calib)
 *   R1 render hand cases          text, spans and guarded ids == HF; refusals by key
 *   R2 render corpus              every L216 case, two configurations: sha1(text+spans),
 *                                 sha1(ids), refusal keys == HF, per case file   (--cases)
 *   P1 output parser round trip   every assistant turn of the corpus rendered, parsed back,
 *                                 re-rendered: byte-identical; any chunking gives the same
 *                                 events   (--cases)
 *   P2 output parser units        malformed / truncated / split-marker outputs
 *   E1 effort resolution          the API's effort / thinking fields -> the template's efforts
 *   C1 turn-by-turn composition   head + turns + sampled turns + closes == the full render: text and ids
 *
 * usage: qwen_chat_gate --tok DIR --vectors DIR [--cases DIR] [--calib FILE]
 *        DIR = the checkpoint's tokenizer.json + generation_config.json */
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <algorithm>
#include <map>
#include <string>
#include <vector>

#include "../src/lib/qwen_tokenizer.h"
#include "../src/lib/pyjson.h"
#include "../src/lib/qwen_chat.h"
#include "../src/lib/sha1.hpp"

static int g_fail = 0;
static int g_checks = 0;

static void fail(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "  FAIL: ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    g_fail++;
}

#define CHECK(cond, ...)                 \
    do {                                 \
        g_checks++;                      \
        if (!(cond)) fail(__VA_ARGS__);  \
    } while (0)

static bool read_file(const std::string &path, std::string *out) {
    FILE *f = fopen(path.c_str(), "rb");
    if (!f) return false;
    char buf[1 << 16];
    size_t n;
    out->clear();
    while ((n = fread(buf, 1, sizeof buf, f)) > 0) out->append(buf, n);
    fclose(f);
    return true;
}

static pyjson_value load_json(const std::string &path) {
    std::string text;
    if (!read_file(path, &text)) {
        fprintf(stderr, "qwen_chat_gate: cannot read %s\n", path.c_str());
        exit(2);
    }
    pyjson_value v;
    char err[200];
    if (!pyjson_parse(text.data(), text.size(), &v, err, sizeof err)) {
        fprintf(stderr, "qwen_chat_gate: %s: %s\n", path.c_str(), err);
        exit(2);
    }
    return v;
}

static std::string sha1_hex(const std::string &s) {
    char hex[41];
    pulsar::Sha1::bytes_hex(s.data(), s.size(), hex);
    return hex;
}

static std::string ids_text(const std::vector<int> &ids) {
    std::string s;
    char b[16];
    for (int id : ids) {
        snprintf(b, sizeof b, "%d,", id);
        s += b;
    }
    return s;
}

static std::vector<int> json_ids(const pyjson_value &v) {
    std::vector<int> ids;
    for (const auto &x : v.a) ids.push_back(atoi(x.num.c_str()));
    return ids;
}

static std::vector<pulsar_text_span> json_spans(const pyjson_value &v) {
    std::vector<pulsar_text_span> spans;
    for (const auto &x : v.a) spans.push_back({(uint32_t)atoi(x.a[0].num.c_str()), (uint32_t)atoi(x.a[1].num.c_str())});
    return spans;
}

static std::vector<int> encode(const qwen_tokenizer *t, const std::string &text,
                               const std::vector<pulsar_text_span> *spans = NULL) {
    std::vector<int> ids;
    char err[200];
    if (!qwen_tokenizer_encode(t, text.data(), text.size(), spans ? spans->data() : NULL,
                               spans ? (uint32_t)spans->size() : 0, &ids, err, sizeof err))
        fail("encode refused: %s", err);
    return ids;
}

static std::string first_diff(const std::vector<int> &a, const std::vector<int> &b) {
    size_t i = 0;
    while (i < a.size() && i < b.size() && a[i] == b[i]) i++;
    char m[160];
    snprintf(m, sizeof m, "len %zu vs %zu, first difference at %zu (%d vs %d)", a.size(), b.size(), i,
             i < a.size() ? a[i] : -1, i < b.size() ? b[i] : -1);
    return m;
}

/* ---- the API conversation -> renderer input ---------------------------------- */

struct conv {
    std::vector<qwen_msg_in> msgs;
    std::vector<std::vector<qwen_tool_call_in>> calls;
    std::vector<std::vector<uint32_t>> image_at;   /* L268: per message, where its images sit in its content */
    std::vector<std::string> store;   /* owned strings; reserved up front so c_str() stays put */
    std::string tools;
    bool has_tools = false;
};

static const char *keep(conv *c, const std::string &s) {
    c->store.push_back(s);
    return c->store.back().c_str();
}

static void build_conv(const pyjson_value &messages, const pyjson_value *tools, conv *c) {
    size_t strings = 1;
    for (const auto &m : messages.a) {
        strings += 4;
        if (const pyjson_value *tc = m.get("tool_calls")) strings += 2 * tc->a.size();
    }
    c->store.reserve(strings);
    c->msgs.resize(messages.a.size());
    c->calls.resize(messages.a.size());
    c->image_at.resize(messages.a.size());
    for (size_t i = 0; i < messages.a.size(); i++) {
        const pyjson_value &m = messages.a[i];
        qwen_msg_in &q = c->msgs[i];
        q = {};
        const pyjson_value *role = m.get("role");
        q.role = keep(c, role ? role->s : "");
        const pyjson_value *content = m.get("content");
        q.content = content && content->kind == pyjson_value::STR ? keep(c, content->s) : NULL;
        if (content && content->kind == pyjson_value::ARR) {
            /* L268: content parts -- the text concatenated, each image's offset in it */
            std::string text;
            for (const auto &part : content->a) {
                const pyjson_value *type = part.get("type");
                if (type && type->s == "image") {
                    c->image_at[i].push_back((uint32_t)text.size());
                } else if (const pyjson_value *t = part.get("text")) {
                    text += t->s;
                }
            }
            q.content = keep(c, text);
            q.image_at = c->image_at[i].empty() ? NULL : c->image_at[i].data();
            q.n_images = (int)c->image_at[i].size();
        }
        const pyjson_value *reasoning = m.get("reasoning_content");
        q.reasoning = reasoning && reasoning->kind == pyjson_value::STR ? keep(c, reasoning->s) : NULL;
        if (const pyjson_value *tcs = m.get("tool_calls")) {
            for (const auto &tc : tcs->a) {
                const pyjson_value *fn = tc.get("function");
                if (!fn) fn = &tc;
                const pyjson_value *name = fn->get("name");
                const pyjson_value *args = fn->get("arguments");
                std::string a;
                if (args && args->kind == pyjson_value::STR) a = args->s;
                else if (args) pyjson_dump(*args, &a);
                c->calls[i].push_back({keep(c, name ? name->s : ""), keep(c, a)});
            }
            q.calls = c->calls[i].data();
            q.n_calls = (int)c->calls[i].size();
        }
    }
    if (tools && tools->kind != pyjson_value::NUL) {
        c->has_tools = true;
        if (tools->kind == pyjson_value::STR) c->tools = tools->s;
        else pyjson_dump(*tools, &c->tools);
    }
}

static qwen_effort effort_of(const std::string &name) {
    if (name == "default") return qwen_effort_default();
    qwen_effort e;
    if (!qwen_effort_parse(name.c_str(), &e)) {
        fprintf(stderr, "qwen_chat_gate: bad effort %s\n", name.c_str());
        exit(2);
    }
    return e;
}

static bool render(const conv &c, qwen_effort effort, bool gen, qwen_render_out *out, std::string *refusal) {
    qwen_render_in in;
    in.msgs = c.msgs.data();
    in.n_msgs = (int)c.msgs.size();
    in.tools_json = c.has_tools ? c.tools.c_str() : NULL;
    in.effort = effort;
    in.add_generation_prompt = gen;
    char err[400];
    if (qwen_chat_render(in, out, err, sizeof err)) return true;
    const char *colon = strchr(err, ':');
    refusal->assign(err, colon ? (size_t)(colon - err) : strlen(err));
    return false;
}

static std::string spans_text(const std::vector<pulsar_text_span> &spans) {
    std::string s;
    char b[32];
    for (size_t i = 0; i < spans.size(); i++) {
        snprintf(b, sizeof b, "%s%u-%u", i ? "," : "", spans[i].lo, spans[i].hi);
        s += b;
    }
    return s;
}

/* ---- sections ---------------------------------------------------------------- */

static void t1_adversarial(const qwen_tokenizer *t, const std::string &dir) {
    const pyjson_value v = load_json(dir + "/tok_adversarial.json");
    int bad = 0;
    for (const auto &c : v.a) {
        const std::string &text = c.get("text")->s;
        const std::vector<int> want = json_ids(*c.get("ids"));
        const std::vector<int> got = encode(t, text);
        g_checks++;
        if (got != want) {
            std::string q;
            pyjson_dump_string(text.data(), std::min<size_t>(text.size(), 80), &q);
            if (bad++ < 10) fail("T1 %s: %s", q.c_str(), first_diff(got, want).c_str());
        }
    }
    printf("T1 adversarial strings: %zu, %d mismatched\n", v.a.size(), bad);
}

static void t2_spans(const qwen_tokenizer *t, const std::string &dir) {
    const pyjson_value v = load_json(dir + "/tok_spans.json");
    int bad = 0, guarded = 0;
    for (const auto &c : v.a) {
        const std::string &text = c.get("text")->s;
        const std::vector<pulsar_text_span> spans = json_spans(*c.get("spans"));
        const std::vector<int> want = json_ids(*c.get("ids"));
        const std::vector<int> got = encode(t, text, &spans);
        g_checks++;
        if (got != want) {
            bad++;
            fail("T2 %s", first_diff(got, want).c_str());
        }
        guarded += encode(t, text) != got;
    }
    printf("T2 span guard: %zu cases (%d where the guard changes the ids), %d mismatched\n", v.a.size(), guarded,
           bad);
}

static void t3_sweep(const qwen_tokenizer *t, const std::string &dir) {
    std::string tsv;
    if (!read_file(dir + "/tok_sweep.tsv", &tsv)) { fail("T3: no tok_sweep.tsv"); return; }
    int chunks = 0, bad = 0;
    long total = 0;
    for (size_t pos = 0; pos < tsv.size();) {
        const size_t nl = tsv.find('\n', pos);
        const std::string line = tsv.substr(pos, nl - pos);
        pos = nl + 1;
        int chunk = 0, n = 0;
        char sha[64];
        if (sscanf(line.c_str(), "%d\t%d\t%63s", &chunk, &n, sha) != 3) continue;
        std::string text;
        for (uint32_t cp = (uint32_t)chunk * 4096; cp < (uint32_t)chunk * 4096 + 4096; cp++) {
            if (cp >= 0xd800 && cp <= 0xdfff) continue;
            std::string c;
            if (cp < 0x80) c.push_back((char)cp);
            else if (cp < 0x800) { c.push_back((char)(0xc0 | (cp >> 6))); c.push_back((char)(0x80 | (cp & 0x3f))); }
            else if (cp < 0x10000) {
                c.push_back((char)(0xe0 | (cp >> 12))); c.push_back((char)(0x80 | ((cp >> 6) & 0x3f)));
                c.push_back((char)(0x80 | (cp & 0x3f)));
            } else {
                c.push_back((char)(0xf0 | (cp >> 18))); c.push_back((char)(0x80 | ((cp >> 12) & 0x3f)));
                c.push_back((char)(0x80 | ((cp >> 6) & 0x3f))); c.push_back((char)(0x80 | (cp & 0x3f)));
            }
            text += "x" + c + c + c + " " + c + "1'" + c + "\n";
        }
        const std::vector<int> ids = encode(t, text);
        total += (long)ids.size();
        chunks++;
        g_checks++;
        if ((int)ids.size() != n || sha1_hex(ids_text(ids)) != sha) {
            bad++;
            fail("T3 chunk %d (U+%04X..): %zu ids vs HF %d", chunk, chunk * 4096, ids.size(), n);
        }
    }
    printf("T3 codepoint sweep: %d chunks, %ld tokens, %d mismatched\n", chunks, total, bad);
}

static void t4_calib(const qwen_tokenizer *t, const std::string &dir, const std::string &calib) {
    std::string tsv, rows;
    if (!read_file(dir + "/tok_calib.tsv", &tsv) || !read_file(calib, &rows)) {
        fail("T4: cannot read tok_calib.tsv or %s", calib.c_str());
        return;
    }
    std::vector<std::pair<int, std::string>> want;
    for (size_t pos = 0; pos < tsv.size();) {
        const size_t nl = tsv.find('\n', pos);
        int idx, n;
        char sha[64];
        if (sscanf(tsv.substr(pos, nl - pos).c_str(), "%d\t%d\t%63s", &idx, &n, sha) == 3) want.push_back({n, sha});
        pos = nl + 1;
    }
    int row = 0, bad = 0;
    long total = 0;
    for (size_t pos = 0; pos < rows.size();) {
        const size_t nl = rows.find('\n', pos);
        const std::string line = rows.substr(pos, nl - pos);
        pos = nl == std::string::npos ? rows.size() : nl + 1;
        if (line.empty()) continue;
        pyjson_value r;
        char err[200];
        if (!pyjson_parse(line.data(), line.size(), &r, err, sizeof err)) { fail("T4 row %d: %s", row, err); row++; continue; }
        const std::vector<int> ids = encode(t, r.get("text")->s);
        total += (long)ids.size();
        g_checks++;
        if (row >= (int)want.size() || (int)ids.size() != want[(size_t)row].first ||
            sha1_hex(ids_text(ids)) != want[(size_t)row].second) {
            bad++;
            fail("T4 row %d: %zu ids", row, ids.size());
        }
        row++;
    }
    CHECK(row == (int)want.size(), "T4: %d rows vs %zu golden", row, want.size());
    printf("T4 calibration corpus: %d rows, %ld tokens, %d mismatched\n", row, total, bad);
}

static void r1_hand(const qwen_tokenizer *t, const std::string &dir) {
    const pyjson_value v = load_json(dir + "/render_cases.json");
    int bad = 0, refusals = 0, guarded = 0;
    for (const auto &c : v.a) {
        const std::string &name = c.get("name")->s;
        conv cv;
        build_conv(*c.get("messages"), c.get("tools"), &cv);
        qwen_render_out out;
        std::string refusal;
        const bool ok = render(cv, effort_of(c.get("effort")->s), c.get("gen")->b, &out, &refusal);
        const pyjson_value *ex = c.get("expect");
        const int before = g_fail;
        g_checks++;
        if (const pyjson_value *want_refusal = ex->get("refusal")) {
            refusals++;
            if (ok || refusal != want_refusal->s)
                fail("R1 %s: expected refusal %s, got %s", name.c_str(), want_refusal->s.c_str(),
                     ok ? "a render" : refusal.c_str());
        } else if (!ok) {
            fail("R1 %s: refused (%s)", name.c_str(), refusal.c_str());
        } else {
            const std::string &want = ex->get("text")->s;
            if (out.text != want) {
                size_t i = 0;
                while (i < out.text.size() && i < want.size() && out.text[i] == want[i]) i++;
                std::string ours, theirs;
                pyjson_dump_string(out.text.data() + i, std::min<size_t>(60, out.text.size() - i), &ours);
                pyjson_dump_string(want.data() + i, std::min<size_t>(60, want.size() - i), &theirs);
                fail("R1 %s: text differs at byte %zu: ours %s vs HF %s", name.c_str(), i, ours.c_str(), theirs.c_str());
            }
            const std::vector<pulsar_text_span> want_spans = json_spans(*ex->get("spans"));
            if (spans_text(out.spans) != spans_text(want_spans))
                fail("R1 %s: spans %s vs HF %s", name.c_str(), spans_text(out.spans).c_str(),
                     spans_text(want_spans).c_str());
            const std::vector<int> ids = encode(t, out.text, &out.spans);
            const std::vector<int> want_ids = json_ids(*ex->get("ids"));
            if (ids != want_ids) fail("R1 %s: ids %s", name.c_str(), first_diff(ids, want_ids).c_str());
            guarded += !ex->get("hf_ids_equal")->b;
        }
        bad += g_fail != before;
    }
    printf("R1 render hand cases: %zu (%d refusals, %d where the span guard departs from HF's whole-text "
           "encode), %d mismatched\n", v.a.size(), refusals, guarded, bad);
}

static void r2_corpus(const qwen_tokenizer *t, const std::string &dir, const std::string &cases_dir) {
    std::string tsv;
    if (!read_file(dir + "/render_corpus.tsv", &tsv)) { fail("R2: no render_corpus.tsv"); return; }
    static const char *efforts[] = {"none", "low", "medium", "xhigh"};
    int lines = 0, bad = 0, cases_total = 0, rendered_total = 0;
    long tokens_total = 0;
    std::map<std::string, int> refusals_total;
    std::string cur_file;
    pyjson_value cases;
    for (size_t pos = 0; pos < tsv.size();) {
        const size_t nl = tsv.find('\n', pos);
        const std::string line = tsv.substr(pos, nl - pos);
        pos = nl + 1;
        if (line.empty() || line[0] == '#') continue;
        std::vector<std::string> f;
        for (size_t a = 0;;) {
            const size_t b = line.find('\t', a);
            f.push_back(line.substr(a, b - a));
            if (b == std::string::npos) break;
            a = b + 1;
        }
        if (f.size() != 9) { fail("R2: bad golden line"); continue; }
        if (f[0] != cur_file) {
            cases = load_json(cases_dir + "/" + f[0]);
            cur_file = f[0];
        }
        const bool cfg_b = f[1] == "B";
        pulsar::Sha1 ht, hi;
        int ok = 0, nguard = 0;
        long ntok = 0;
        std::map<std::string, int> refused;
        for (size_t idx = 0; idx < cases.a.size(); idx++) {
            const pyjson_value &c = cases.a[idx];
            conv cv;
            build_conv(*c.get("messages"), c.get("tools"), &cv);
            if (cv.has_tools) {   /* the generator passes tools only when the list is non-empty */
                const pyjson_value *tl = c.get("tools");
                if (tl->kind == pyjson_value::ARR && tl->a.empty()) cv.has_tools = false;
            }
            const qwen_effort effort = cfg_b ? effort_of(efforts[idx % 4]) : qwen_effort_default();
            qwen_render_out out;
            std::string refusal;
            char line_buf[512];
            if (!render(cv, effort, cfg_b, &out, &refusal)) {
                refused[refusal]++;
                snprintf(line_buf, sizeof line_buf, "%zu refuse %s\n", idx, refusal.c_str());
                ht.update(line_buf, strlen(line_buf));
                continue;
            }
            ok++;
            const std::string l = std::to_string(idx) + " " + sha1_hex(out.text) + " " + spans_text(out.spans) + "\n";
            ht.update(l.data(), l.size());
            const std::vector<int> ids = encode(t, out.text, &out.spans);
            nguard += encode(t, out.text) != ids;
            ntok += (long)ids.size();
            const std::string li = std::to_string(idx) + " " + sha1_hex(ids_text(ids)) + "\n";
            hi.update(li.data(), li.size());
        }
        uint8_t d1[20], d2[20];
        ht.final(d1);
        hi.final(d2);
        char h1[41], h2[41];
        for (int i = 0; i < 20; i++) { snprintf(h1 + 2 * i, 3, "%02x", d1[i]); snprintf(h2 + 2 * i, 3, "%02x", d2[i]); }
        std::string ref;
        for (const auto &kv : refused) ref += (ref.empty() ? "" : ",") + kv.first + "=" + std::to_string(kv.second);
        if (ref.empty()) ref = "-";
        lines++;
        cases_total += (int)cases.a.size();
        rendered_total += ok;
        tokens_total += ntok;
        for (const auto &kv : refused) refusals_total[kv.first] += kv.second;
        g_checks++;
        if (std::to_string(ok) != f[3] || ref != f[4] || h1 != f[5] || h2 != f[6] || std::to_string(ntok) != f[7] ||
            std::to_string(nguard) != f[8]) {
            bad++;
            fail("R2 %s cfg %s: rendered %d/%s refusals %s/%s text %s ids %s tokens %ld/%s guarded %d/%s",
                 f[0].c_str(), f[1].c_str(), ok, f[3].c_str(), ref.c_str(), f[4].c_str(),
                 h1 == f[5] ? "=" : "DIFF", h2 == f[6] ? "=" : "DIFF", ntok, f[7].c_str(), nguard, f[8].c_str());
        }
    }
    std::string ref;
    for (const auto &kv : refusals_total) ref += " " + kv.first + "=" + std::to_string(kv.second);
    printf("R2 render corpus: %d file x config lines, %d cases, %d rendered, %ld tokens, refusals:%s; "
           "%d mismatched\n", lines, cases_total, rendered_total, tokens_total, ref.c_str(), bad);
}

/* ---- the output parser ------------------------------------------------------- */

struct parse_result {
    std::string reasoning, content, ev_reasoning, ev_content, calls, errors;
    int begins = 0;
};

static parse_result run_parser(const std::string &out, bool thinking, const char *tools, const std::vector<size_t> &cuts) {
    qwen_output_parser p;
    char err[200];
    parse_result r;
    if (!p.init(thinking, tools, err, sizeof err)) { fail("parser init: %s", err); return r; }
    std::vector<qwen_out_event> ev;
    size_t at = 0;
    for (size_t cut : cuts) {
        p.feed(out.data() + at, cut - at, &ev);
        at = cut;
    }
    p.feed(out.data() + at, out.size() - at, &ev);
    p.finish(&ev);
    std::string streamed;   /* L284 P5: the call's TOOL_ARGS fragments, one per closed parameter */
    int fragments = 0;
    for (const auto &e : ev) {
        switch (e.kind) {
        case qwen_out_event::REASONING: r.ev_reasoning += e.text; break;
        case qwen_out_event::CONTENT: r.ev_content += e.text; break;
        case qwen_out_event::TOOL_BEGIN: r.begins++; streamed.clear(); fragments = 0; break;
        case qwen_out_event::TOOL_ARGS: streamed += e.text; fragments++; break;
        case qwen_out_event::TOOL_END: {
            r.calls += std::to_string(e.index) + ":" + e.name + ":" + e.arguments + "\n";
            /* the fragments + "}" are the arguments, byte for byte, unless a key repeated (streamed twice) */
            pyjson_value a;
            char jerr[8];
            if (pyjson_parse(e.arguments.data(), e.arguments.size(), &a, jerr, sizeof jerr) &&
                (int)a.o.size() == fragments)
                CHECK((fragments ? streamed + "}" : std::string("{}")) == e.arguments,
                      "parser: TOOL_ARGS fragments do not add up to the arguments");
            break;
        }
        case qwen_out_event::ERROR: r.errors += e.text + "\n"; break;
        }
    }
    r.reasoning = p.reasoning();
    r.content = p.content();
    std::string direct;
    for (size_t i = 0; i < p.calls().size(); i++)
        direct += std::to_string(i) + ":" + p.calls()[i].name + ":" + p.calls()[i].arguments + "\n";
    CHECK(r.ev_reasoning == r.reasoning && r.ev_content == r.content,
          "parser: event deltas do not add up to the result");
    if (r.errors.empty()) CHECK(direct == r.calls, "parser: TOOL_END events disagree with calls()");
    return r;
}

static bool contains(const char *s, const char *needle) { return s && strstr(s, needle); }

static void p1_roundtrip(const std::string &cases_dir, const std::string &dir) {
    std::string tsv;
    if (!read_file(dir + "/render_corpus.tsv", &tsv)) return;
    int turns = 0, ambiguous = 0, bad = 0, with_calls = 0;
    unsigned rng = 12345;
    std::string last;
    for (size_t pos = 0; pos < tsv.size();) {
        const size_t nl = tsv.find('\n', pos);
        const std::string line = tsv.substr(pos, nl - pos);
        pos = nl + 1;
        if (line.empty() || line[0] == '#') continue;
        const std::string file = line.substr(0, line.find('\t'));
        if (file == last) continue;
        last = file;
        const pyjson_value cases = load_json(cases_dir + "/" + file);
        for (const auto &c : cases.a) {
            conv cv;
            build_conv(*c.get("messages"), c.get("tools"), &cv);
            for (size_t i = 0; i < cv.msgs.size(); i++) {
                const qwen_msg_in &m = cv.msgs[i];
                if (strcmp(m.role, "assistant")) continue;
                /* the turn as the model would have sampled it: [user, this assistant] */
                conv one;
                one.store.reserve(2);
                qwen_msg_in user = {};
                user.role = "user";
                user.content = "q";
                one.msgs = {user, m};
                one.tools = cv.tools;
                one.has_tools = cv.has_tools;
                qwen_render_out out;
                std::string refusal;
                if (!render(one, QWEN_EFFORT_XHIGH, false, &out, &refusal)) continue;   /* refused turns: R2 */
                bool amb = contains(m.reasoning, "</think>") || contains(m.content, "<tool_call>") ||
                           contains(m.content, "</think>");
                for (int k = 0; k < m.n_calls; k++)
                    amb |= contains(m.calls[k].arguments, "</parameter>") || contains(m.calls[k].arguments, "</function>") ||
                           contains(m.calls[k].arguments, "</tool_call>") || contains(m.calls[k].name, ">");
                if (amb) { ambiguous++; continue; }
                const std::string head = "<|im_start|>assistant\n<think>\n";
                const size_t a = out.text.rfind(head);
                const std::string sampled = out.text.substr(a + head.size(), out.text.size() - a - head.size() -
                                                                                 strlen("<|im_end|>\n"));
                turns++;
                with_calls += m.n_calls > 0;
                const char *tools = one.has_tools ? one.tools.c_str() : NULL;
                const parse_result whole = run_parser(sampled, true, tools, {});
                std::vector<size_t> bytes;
                for (size_t k = 1; k < sampled.size(); k++) bytes.push_back(k);
                const parse_result each = run_parser(sampled, true, tools, bytes);
                std::vector<size_t> rnd;
                for (size_t k = 0; k < sampled.size();) {
                    rng = rng * 1103515245u + 12345u;
                    k += 1 + (rng >> 16) % 23;
                    if (k < sampled.size()) rnd.push_back(k);
                }
                const parse_result random = run_parser(sampled, true, tools, rnd);
                const int before = g_fail;
                g_checks++;
                if (!whole.errors.empty()) fail("P1 %s: parser error: %s", file.c_str(), whole.errors.c_str());
                if (each.reasoning != whole.reasoning || each.content != whole.content || each.calls != whole.calls ||
                    random.reasoning != whole.reasoning || random.content != whole.content || random.calls != whole.calls)
                    fail("P1 %s: chunking changed the parse", file.c_str());
                /* re-render what the parser read */
                conv back;
                back.store.reserve(4 + 2 * (size_t)std::count(whole.calls.begin(), whole.calls.end(), '\n'));
                qwen_msg_in r = {};
                r.role = "assistant";
                r.content = keep(&back, whole.content);
                r.reasoning = keep(&back, whole.reasoning);
                std::vector<qwen_tool_call_in> calls;
                for (size_t s = 0; s < whole.calls.size();) {
                    const size_t e = whole.calls.find('\n', s);
                    const std::string row = whole.calls.substr(s, e - s);
                    const size_t c1 = row.find(':'), c2 = row.find(':', c1 + 1);
                    calls.push_back({keep(&back, row.substr(c1 + 1, c2 - c1 - 1)), keep(&back, row.substr(c2 + 1))});
                    s = e + 1;
                }
                r.calls = calls.data();
                r.n_calls = (int)calls.size();
                back.msgs = {user, r};
                back.tools = one.tools;
                back.has_tools = one.has_tools;
                qwen_render_out again;
                if (!render(back, QWEN_EFFORT_XHIGH, false, &again, &refusal)) fail("P1 %s: re-render refused: %s", file.c_str(), refusal.c_str());
                else if (again.text != out.text) {
                    size_t d = 0;
                    while (d < again.text.size() && d < out.text.size() && again.text[d] == out.text[d]) d++;
                    std::string x, y;
                    pyjson_dump_string(again.text.data() + d, std::min<size_t>(60, again.text.size() - d), &x);
                    pyjson_dump_string(out.text.data() + d, std::min<size_t>(60, out.text.size() - d), &y);
                    fail("P1 %s: re-render differs at %zu: %s vs %s", file.c_str(), d, x.c_str(), y.c_str());
                }
                if (g_fail != before && ++bad > 20) { printf("P1: stopping after 20 failures\n"); return; }
            }
        }
    }
    printf("P1 output parser round trip: %d assistant turns (%d with tool calls; %d ambiguous by construction "
           "skipped), whole / byte-by-byte / random chunking; %d mismatched\n", turns, with_calls, ambiguous, bad);
}

static void p2_units(void) {
    const char *tools = R"([{"type": "function", "function": {"name": "f", "parameters": {"type": "object", "properties": )"
                        R"({"s": {"type": "string"}, "n": {"type": "integer"}, "u": {"type": ["string", "null"]}}}}}])";
    struct unit {
        const char *name;
        bool thinking;
        const char *out;
        const char *reasoning, *content, *calls, *error;   /* error: a substring of the ERROR text, or NULL */
    } units[] = {
        {"plain", true, "let me think\n</think>\n\nThe answer.", "let me think", "The answer.", "", NULL},
        {"thinking_off", false, "Just content.  ", "", "Just content.", "", NULL},
        {"no_close_think", true, "cut off mid thought   ", "cut off mid thought", "", "", NULL},
        {"interior_ws_kept", true, "a \n b\n</think>\n\nx  \n y\n", "a \n b", "x  \n y", "", NULL},
        {"unicode_ws", true, "　r \n</think> c\u0085", "r", "c", "", NULL},
        {"call", true, "r\n</think>\n\nOk.\n\n<tool_call>\n<function=f>\n<parameter=s>\n12\n</parameter>\n"
                       "<parameter=n>\n12\n</parameter>\n<parameter=x>\n{\"a\": 1}\n</parameter>\n"
                       "<parameter=y>\n{\"a\":1}\n</parameter>\n<parameter=u>\nnull\n</parameter>\n</function>\n</tool_call>",
         "r", "Ok.", "0:f:{\"s\": \"12\", \"n\": 12, \"x\": {\"a\": 1}, \"y\": \"{\\\"a\\\":1}\", \"u\": \"null\"}\n", NULL},
        {"two_calls_no_content", true, "</think>\n\n<tool_call>\n<function=f>\n</function>\n</tool_call>\n<tool_call>\n"
                                       "<function=g>\n<parameter=k>\n\n\nv\n\n\n</parameter>\n</function>\n</tool_call>",
         "", "", "0:f:{}\n1:g:{\"k\": \"\\n\\nv\\n\\n\"}\n", NULL},
        {"dup_param", true, "</think><tool_call><function=g><parameter=a>1</parameter><parameter=b>2</parameter>"
                            "<parameter=a>3</parameter></function></tool_call>",
         "", "", "0:g:{\"a\": 3, \"b\": 2}\n", NULL},
        {"text_after_call", true, "</think>\n\n<tool_call>\n<function=f>\n</function>\n</tool_call>\nextra words",
         "", "extra words", "0:f:{}\n", NULL},
        {"unterminated", true, "</think>\n\n<tool_call>\n<function=f>\n<parameter=s>\nabc", "", "", "", "unterminated tool call 0"},
        {"no_function", true, "</think><tool_call>\nhello\n</tool_call>", "", "", "", "expected <function="},
        {"junk_after_function", true, "</think><tool_call><function=f></function>junk</tool_call>", "", "", "",
         "text after </function>"},
        {"unterminated_param", true, "</think><tool_call><function=f><parameter=s>x</function></tool_call>", "", "", "",
         "unterminated parameter value"},
        {"marker_text_in_reasoning", true, "I could <tool_call> here\n</think>\n\nno", "I could <tool_call> here", "no", "",
         NULL},
        {"partial_marker_at_end", true, "r</think>tail </thi", "r", "tail </thi", "", NULL},
        {"quoted_untyped_value_stays_string", true, "</think><tool_call>\n<function=g>\n<parameter=x>\n\"hi\"\n"
                                                    "</parameter>\n</function>\n</tool_call>",
         "", "", "0:g:{\"x\": \"\\\"hi\\\"\"}\n", NULL},
        {"lookalike_markers", true, "</thinking> <tool_calls>\n</think>c </tool_call> <tool_cal", "</thinking> <tool_calls>",
         "c </tool_call> <tool_cal", "", NULL},
    };
    int bad = 0;
    for (const auto &u : units) {
        const std::string out = u.out;
        std::vector<size_t> bytes;
        for (size_t k = 1; k < out.size(); k++) bytes.push_back(k);
        for (int pass = 0; pass < 2; pass++) {
            const parse_result r = run_parser(out, u.thinking, tools, pass ? bytes : std::vector<size_t>{});
            const int before = g_fail;
            CHECK(r.reasoning == u.reasoning, "P2 %s: reasoning [%s]", u.name, r.reasoning.c_str());
            CHECK(r.content == u.content, "P2 %s: content [%s]", u.name, r.content.c_str());
            if (!u.error) {
                CHECK(r.calls == u.calls, "P2 %s: calls [%s]", u.name, r.calls.c_str());
                CHECK(r.errors.empty(), "P2 %s: unexpected error %s", u.name, r.errors.c_str());
            } else {
                CHECK(strstr(r.errors.c_str(), u.error), "P2 %s: error [%s]", u.name, r.errors.c_str());
            }
            bad += g_fail != before;
        }
    }
    printf("P2 output parser units: %zu outputs x 2 chunkings, %d mismatched\n", sizeof units / sizeof units[0], bad);
}

static void e1_effort(void) {
    struct { const char *name; int thinking; bool ok; qwen_effort want; } u[] = {
        {NULL, -1, true, QWEN_EFFORT_XHIGH}, {NULL, 1, true, QWEN_EFFORT_XHIGH}, {NULL, 0, true, QWEN_EFFORT_NONE},
        {"low", -1, true, QWEN_EFFORT_LOW}, {"medium", 1, true, QWEN_EFFORT_MEDIUM}, {"xhigh", -1, true, QWEN_EFFORT_XHIGH},
        {"none", -1, true, QWEN_EFFORT_NONE}, {"none", 1, false, QWEN_EFFORT_NONE}, {"high", 0, true, QWEN_EFFORT_NONE},
        {"high", -1, false, QWEN_EFFORT_NONE}, {"max", -1, false, QWEN_EFFORT_NONE}, {"minimal", 1, false, QWEN_EFFORT_NONE},
        {"50", -1, false, QWEN_EFFORT_NONE}, {"", -1, false, QWEN_EFFORT_NONE}, {"XHIGH", -1, false, QWEN_EFFORT_NONE},
    };
    int bad = 0;
    for (const auto &c : u) {
        qwen_effort e = QWEN_EFFORT_LOW;
        char err[200] = "";
        const bool ok = qwen_effort_resolve(c.name, c.thinking, &e, err, sizeof err);
        const int before = g_fail;
        CHECK(ok == c.ok && (!ok || e == c.want), "E1 effort %s thinking %d: %s %s", c.name ? c.name : "(unsent)",
              c.thinking, ok ? qwen_effort_name(e) : "refused", err);
        CHECK(ok || strstr(err, "low, medium or xhigh"), "E1 effort %s: refusal does not list the names",
              c.name ? c.name : "(unsent)");
        bad += g_fail != before;
    }
    printf("E1 effort resolution: %zu requests, %d mismatched\n", sizeof u / sizeof u[0], bad);
}

/* L284 P14: a conversation built turn by turn -- the head, each turn (qwen_chat_render_turn), each sampled
 * assistant turn followed by its close "<|im_end|>\n" -- is the full render byte for byte, and every piece the
 * front end renders (all but the sampled turns, whose ids are the model's) tokenizes on its own to exactly the
 * full render's ids over its bytes: its edges are token edges of the whole, so a transcript appended piece by
 * piece is the full render and its KV continues across turns.  The one edge that is the model's is where a
 * generation prompt meets the sampled turn: the whole text may merge across it (an empty reasoning's
 * "<think>\n" + "\n</think>" holds one "\n\n" token), so there the piece's last token is not compared. */
static void c1_composition(const qwen_tokenizer *t) {
    struct piece { std::string text; std::vector<pulsar_text_span> spans; bool sampled; };
    const qwen_tool_call_in call = {"read_file", "{\"path\": \"a.txt\", \"lines\": 3}"};
    const std::string note = qwen_system_reminder("Current local date and time: now.");
    const qwen_msg_in convs[][9] = {
        {{"system", "You are terse.", NULL, NULL, 0, NULL, NULL, 0},
         {"user", "Hi there.", NULL, NULL, 0, NULL, NULL, 0},
         {"assistant", "Hello!", "The user greets me.", NULL, 0, NULL, NULL, 0},
         {"user", note.c_str(), NULL, NULL, 0, NULL, NULL, 0},
         {"user", "Read a.txt.", NULL, NULL, 0, NULL, NULL, 0},
         {"assistant", "Reading it.", "Use the tool.", &call, 1, NULL, NULL, 0},
         {"tool", "line one\nline two.", NULL, NULL, 0, NULL, NULL, 0},
         {"tool", "second result", NULL, NULL, 0, NULL, NULL, 0},
         {"user", "Thanks.  Summarize.", NULL, NULL, 0, NULL, NULL, 0}},
        {{"user", "What is 2+2?", NULL, NULL, 0, NULL, NULL, 0},
         {"assistant", "4.", "", NULL, 0, NULL, NULL, 0},
         {"user", "And 3+3?", NULL, NULL, 0, NULL, NULL, 0},
         {"assistant", "6.\n", "  ", NULL, 0, NULL, NULL, 0},
         {"user", "Done.", NULL, NULL, 0, NULL, NULL, 0}},
    };
    const int lens[] = {9, 5};
    const qwen_effort efforts[] = {QWEN_EFFORT_XHIGH, QWEN_EFFORT_MEDIUM, QWEN_EFFORT_LOW, QWEN_EFFORT_NONE};
    int bad = 0, n = 0;
    for (int c = 0; c < 2; c++) {
        for (qwen_effort eff : efforts) {
            const qwen_msg_in *m = convs[c];
            const int len = lens[c];
            const bool thinking = eff != QWEN_EFFORT_NONE;
            char err[300] = "";
            std::vector<piece> pieces;
            qwen_render_out r;
            const bool sys = !strcmp(m[0].role, "system");
            bool ok = qwen_chat_render_head(sys ? m[0].content : NULL, eff, &r, err, sizeof err);
            pieces.push_back({r.text, r.spans, false});
            int i = sys ? 1 : 0;
            while (ok && i < len) {
                int j = i;
                while (j < len && strcmp(m[j].role, "assistant")) j++;
                ok = qwen_chat_render_turn(m + i, j - i, eff, true, &r, err, sizeof err);
                pieces.push_back({r.text, r.spans, false});
                if (!ok || j == len) break;
                /* the sampled turn: what the model wrote past the generation prompt, before its stop token */
                qwen_msg_in a = m[j];
                if (!thinking) a.reasoning = NULL;
                ok = qwen_chat_render_assistant_turn(a, thinking, &r, err, sizeof err);
                if (ok && a.n_calls == 0) r.text.resize(r.text.size() - strlen("<|im_end|>\n"));
                pieces.push_back({r.text, r.spans, true});
                pieces.push_back({"<|im_end|>\n", {}, false});
                i = j + 1;
            }
            std::vector<qwen_msg_in> full_msgs(m, m + len);
            if (!thinking)
                for (auto &x : full_msgs) x.reasoning = NULL;
            qwen_render_out full;
            ok = ok && qwen_chat_render({full_msgs.data(), len, NULL, eff, true}, &full, err, sizeof err);
            std::string text;
            for (const piece &p : pieces) text += p.text;
            const int before = g_fail;
            CHECK(ok, "C1 conversation %d effort %s: refused: %s", c, qwen_effort_name(eff), err);
            CHECK(!ok || text == full.text, "C1 conversation %d effort %s: the turns' text is not the full render",
                  c, qwen_effort_name(eff));
            if (ok && text == full.text) {
                /* the full render's ids with the byte offset each starts at */
                const std::vector<int> want = encode(t, full.text, &full.spans);
                std::vector<size_t> at(want.size() + 1, 0);
                for (size_t k = 0; k < want.size(); k++) {
                    size_t nb = 0;
                    qwen_tokenizer_token_bytes(t, want[k], &nb);
                    at[k + 1] = at[k] + nb;
                }
                size_t lo = 0;
                for (size_t q = 0; q < pieces.size(); q++) {
                    const piece &p = pieces[q];
                    const size_t hi = lo + p.text.size();
                    if (!p.sampled && !p.text.empty()) {
                        const bool open_end = q + 1 < pieces.size() && pieces[q + 1].sampled;
                        std::vector<int> got = encode(t, p.text, &p.spans);
                        if (open_end) got.pop_back();
                        size_t got_hi = lo;
                        for (int id : got) {
                            size_t nb = 0;
                            qwen_tokenizer_token_bytes(t, id, &nb);
                            got_hi += nb;
                        }
                        const auto a = std::find(at.begin(), at.end(), lo);
                        const auto b = std::find(at.begin(), at.end(), got_hi);
                        const bool edges = a != at.end() && b != at.end();
                        const std::vector<int> whole = edges ? std::vector<int>(want.begin() + (a - at.begin()),
                                                                                want.begin() + (b - at.begin()))
                                                             : std::vector<int>();
                        CHECK(edges && got == whole, "C1 conversation %d effort %s piece %zu [%zu, %zu): %s", c,
                              qwen_effort_name(eff), q, lo, hi,
                              edges ? first_diff(got, whole).c_str() : "its edges are not token edges of the whole");
                    }
                    lo = hi;
                }
            }
            bad += g_fail != before;
            n++;
        }
    }
    printf("C1 turn-by-turn composition: %d conversations x efforts, %d mismatched\n", n, bad);
}

int main(int argc, char **argv) {
    std::string tok_dir, vec_dir, cases_dir, calib;
    for (int i = 1; i < argc; i++) {
        const std::string a = argv[i];
        if (a == "--tok" && i + 1 < argc) tok_dir = argv[++i];
        else if (a == "--vectors" && i + 1 < argc) vec_dir = argv[++i];
        else if (a == "--cases" && i + 1 < argc) cases_dir = argv[++i];
        else if (a == "--calib" && i + 1 < argc) calib = argv[++i];
        else {
            fprintf(stderr, "usage: qwen_chat_gate --tok DIR --vectors DIR [--cases DIR] [--calib FILE]\n");
            return 2;
        }
    }
    if (tok_dir.empty() || vec_dir.empty()) {
        fprintf(stderr, "usage: qwen_chat_gate --tok DIR --vectors DIR [--cases DIR] [--calib FILE]\n");
        return 2;
    }
    std::string tj, gj;
    if (!read_file(tok_dir + "/tokenizer.json", &tj) || !read_file(tok_dir + "/generation_config.json", &gj)) {
        fprintf(stderr, "qwen_chat_gate: %s must hold tokenizer.json and generation_config.json\n", tok_dir.c_str());
        return 2;
    }
    char err[512];
    qwen_tokenizer *t = qwen_tokenizer_load(tj.data(), tj.size(), gj.data(), gj.size(), err, sizeof err);
    if (!t) {
        fprintf(stderr, "qwen_chat_gate: %s\n", err);
        return 1;
    }
    const pyjson_value meta = load_json(vec_dir + "/meta.json");
    printf("qwen_chat_gate: tokenizer %s (%d ids), goldens from transformers %s / tokenizers %s\n", tok_dir.c_str(),
           qwen_tokenizer_n_tokens(t), meta.get("transformers")->s.c_str(), meta.get("tokenizers")->s.c_str());
    CHECK(qwen_tokenizer_n_tokens(t) == atoi(meta.get("n_tokens")->num.c_str()), "token count %d vs HF %s",
          qwen_tokenizer_n_tokens(t), meta.get("n_tokens")->num.c_str());
    CHECK(json_ids(*meta.get("stop_ids")) == qwen_tokenizer_stop_ids(t), "stop ids differ from generation_config");
    CHECK(qwen_effort_default() == QWEN_EFFORT_XHIGH, "the family default effort is not the template's xhigh");
    printf("stop ids:");
    for (int id : qwen_tokenizer_stop_ids(t)) {
        size_t n = 0;
        const char *b = qwen_tokenizer_token_bytes(t, id, &n);
        printf(" %d %.*s", id, (int)n, b);
    }
    printf("; default effort %s\n", qwen_effort_name(qwen_effort_default()));

    t1_adversarial(t, vec_dir);
    t2_spans(t, vec_dir);
    t3_sweep(t, vec_dir);
    if (!calib.empty()) t4_calib(t, vec_dir, calib);
    else printf("T4 calibration corpus: SKIPPED (no --calib)\n");
    r1_hand(t, vec_dir);
    if (!cases_dir.empty()) {
        r2_corpus(t, vec_dir, cases_dir);
        p1_roundtrip(cases_dir, vec_dir);
    } else {
        printf("R2 render corpus / P1 parser round trip: SKIPPED (no --cases)\n");
    }
    p2_units();
    e1_effort();
    c1_composition(t);
    qwen_tokenizer_free(t);
    printf("\nqwen_chat_gate: %d checks, %d failed -- %s\n", g_checks, g_fail, g_fail ? "FAIL" : "PASS");
    return g_fail ? 1 : 0;
}
