#!/usr/bin/env python3
"""Generate vision-layout goldens from the checkpoint's OWN image_processor.py.

Run this where the Vision-Exp snapshot is readable and torch+PIL are importable
(sparky: /home/claude/Projects/AI/prismaquant/.venv/bin/python).  It imports the
reference module and calls its functions -- it does NOT reimplement them -- so
the C++ port in src/engine/vision.cpp is graded against the authority, not
against a second transcription of it.

    python3 tests/vision_layout_goldens.py <snapshot>/inference > tests/test-vectors/vision-layout-goldens.txt
"""
import sys, math, os

sys.path.insert(0, sys.argv[1])
import image_processor as ip  # noqa: E402

PATCH = 14
RATIO = 3
MAXN = 384


def main():
    out = sys.stdout
    print("# vision-layout goldens -- generated by tests/vision_layout_goldens.py from the")
    print("# checkpoint's inference/image_processor.py (deepseek-ai/DeepSeek-V4-Flash-Vision-Exp).")
    print("# patch=%d ratio=%d max_n_token=%d compress_pad_to=%d" % (PATCH, RATIO, MAXN, ip.COMPRESS_PAD_TO))
    print("# grid  best_h best_w patch ratio n_llm_h n_llm_w num_tokens")
    for bh in (14, 28, 42, 56, 112, 140, 224, 280, 448, 560, 840, 1120, 1680, 4032):
        for bw in (14, 28, 70, 112, 196, 280, 448, 700, 1120, 1680, 4032):
            h, w, n = ip.grid_tokens(bh, bw, PATCH, RATIO)
            print("grid %d %d %d %d %d %d %d" % (bh, bw, PATCH, RATIO, h, w, n))
    print("# solve h w patch ratio max_n n_llm_h n_llm_w best_h best_w num_tokens")
    for (h, w) in ((1024, 768), (768, 1024), (800, 600), (600, 800), (4032, 3024),
                   (3024, 4032), (1920, 1080), (1080, 1920), (224, 224), (100, 5000),
                   (5000, 100), (1, 1), (384, 384), (1024, 1024), (2000, 130)):
        for maxn in (MAXN, 383, 300, 100, 20, 5):
            try:
                a, b, bh, bw, n = ip.solve_resize_ratio(h, w, PATCH, RATIO, maxn)
            except Exception:
                continue
            print("solve %d %d %d %d %d %d %d %d %d %d" % (h, w, PATCH, RATIO, maxn, a, b, bh, bw, n))
    print("# safe h w patch ratio max_n n_llm_h n_llm_w best_h best_w")
    for (h, w) in ((1024, 768), (768, 1024), (800, 600), (4032, 3024), (1920, 1080),
                   (224, 224), (100, 5000), (1, 1), (384, 384), (2000, 130),
                   (147456, 1), (1000, 1000), (56, 56)):
        for maxn in (MAXN, 383, 300, 100, 20, 5):
            best_h = math.ceil(h / PATCH) * PATCH
            best_w = math.ceil(w / PATCH) * PATCH
            try:
                a, b, bh, bw = ip.safe_resize(h, w, best_h, best_w, PATCH, RATIO, maxn)
            except Exception:
                continue
            print("safe %d %d %d %d %d %d %d %d %d" % (h, w, PATCH, RATIO, maxn, a, b, bh, bw))
    print("# block n_llm_h n_llm_w start_pos types... ; perm...")
    for (nh, nw) in ((1, 1), (1, 4), (2, 3), (3, 5), (7, 11), (8, 16), (16, 24), (21, 28)):
        for sp in (0, 1, 2, 3, 5, 17, 101):
            types, perm = ip.build_image_block(nh, nw, sp)
            print("block %d %d %d %s ; %s" % (
                nh, nw, sp,
                " ".join(str(int(t)) for t in types.tolist()),
                " ".join(str(int(p)) for p in perm.tolist())))


if __name__ == "__main__":
    main()
