/* L216 -- DeepSeek-V4-Flash-Vision-Exp image LAYOUT math.
 *
 * A faithful port of the checkpoint's own inference/image_processor.py: the
 * grid arithmetic that decides how many ViT patches an image becomes, how much
 * that image is allowed to shrink to fit the token budget, and how its patches
 * land in the text sequence as sentinel tokens.
 *
 * These are pure functions of the image DIMENSIONS and the block's position in
 * the prompt -- no pixels, no decoder, no GPU -- which is what makes them
 * gradeable directly against the reference.  tests/vision_layout_gate.cpp does
 * exactly that with goldens generated by running image_processor.py itself.
 *
 * AUTHORITY (Tyler, 2026-09-12): the vision path follows the reference, not
 * vLLM's deviations.  In particular the sentinel ids are OUT-OF-VOCAB,
 * `vocab_size + type`, where type is IMAGE_START/PAD/IMAGE/NEWLINE/END = 0..4 --
 * NOT the borrowed in-vocab `<|place_holder_mm_span_0431..0435|>` tokens vLLM
 * substitutes so the ids stay in-vocabulary.  The engine's embed step must
 * therefore zero-mask ids >= vocab_size the way the reference's
 * ParallelEmbedding does (gather row 0, then zero the row); every sentinel
 * position is overwritten before the decoder layers see it. */
#include "pulsar_engine_internal.h"

#include <math.h>
#include <setjmp.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* The DECODER: libpng and libjpeg-turbo, the two libraries Pillow itself
 * decodes with.  Using the same pair is the whole point -- a different JPEG
 * decoder produces different pixels for the same file, and the reference (and
 * the vLLM capture) preprocess with Pillow, so any other choice would put every
 * image feature on a different input with nothing to compare against. */
#include <jpeglib.h>
#include <png.h>

/* The reference's IMAGE_START, IMAGE_PAD, IMAGE, IMAGE_NEW_LINE, IMAGE_END. */
#define VISION_T_IMAGE_START    0
#define VISION_T_IMAGE_PAD      1
#define VISION_T_IMAGE          2
#define VISION_T_IMAGE_NEWLINE  3
#define VISION_T_IMAGE_END      4
#define VISION_COMPRESS_PAD_TO  4

/* image_processor.grid_tokens(): the LLM-token grid the aligner occupies,
 * including the row padding and the compressor-alignment pad. */
pulsar_vision_grid vision_grid_tokens(int best_height, int best_width,
                                      int patch_size, int downsample_ratio) {
    pulsar_vision_grid g;
    g.n_llm_h = (int)ceil((double)(best_height / patch_size) / (double)downsample_ratio);
    g.n_llm_w = (int)ceil((double)(best_width / patch_size) / (double)downsample_ratio);
    int num_tokens = g.n_llm_h * (g.n_llm_w + 1) + 2;
    if (g.n_llm_h % 2 == 1) num_tokens += g.n_llm_w + 1;
    num_tokens += ((g.n_llm_h + 1) / 2) * (g.n_llm_w + 1) % 2 * 2;
    g.num_tokens = num_tokens;
    return g;
}

/* image_processor.solve_resize_ratio(): the largest patch-aligned size whose
 * grid fits `max_n_token`.  float64 throughout, like the reference. */
pulsar_vision_resize vision_solve_resize_ratio(int height, int width,
                                               int patch_size, int downsample_ratio,
                                               int max_n_token) {
    pulsar_vision_resize r;
    const double ratio = (double)height / (double)width;
    const double max_w_float = sqrt((double)(max_n_token - 2) / ratio + 0.25) - 0.5;
    const double max_h_float = max_w_float * ratio;
    int best_width, best_height;
    if (max_w_float < 1.0) {
        const int max_w = 1;
        int max_h = (max_n_token - 2) / (max_w + 1);
        if (max_h % 2 == 1) max_h -= 1;
        best_width = max_w * patch_size * downsample_ratio;
        best_height = max_h * patch_size * downsample_ratio;
    } else if (max_h_float < 2.0) {
        const int max_h = 2;
        const int max_w = ((max_n_token - 2) / max_h) - 1;
        if (max_w <= 1) return (pulsar_vision_resize){0};   /* reference asserts max_w > 1 */
        best_width = max_w * patch_size * downsample_ratio;
        best_height = max_h * patch_size * downsample_ratio;
    } else {
        const int max_w = (int)floor(max_w_float);
        int max_h = (int)floor(max_h_float);
        if (max_h % 2 == 1) max_h -= 1;
        const double beta_w = (double)max_w * patch_size * downsample_ratio / (double)width;
        const double beta_h = (double)max_h * patch_size * downsample_ratio / (double)height;
        const double beta = beta_w < beta_h ? beta_w : beta_h;
        best_width = (int)floor((double)width * beta / patch_size) * patch_size;
        best_height = (int)floor((double)height * beta / patch_size) * patch_size;
    }
    pulsar_vision_grid g = vision_grid_tokens(best_height, best_width, patch_size, downsample_ratio);
    r.n_llm_h = g.n_llm_h;
    r.n_llm_w = g.n_llm_w;
    r.best_height = best_height;
    r.best_width = best_width;
    r.num_tokens = g.num_tokens;
    return r;
}

/* image_processor.safe_resize(): shrink until the grid fits the budget the
 * compressor pad leaves (max_n_token - (COMPRESS_PAD_TO - 1)). */
int vision_safe_resize(int height, int width, int best_height, int best_width,
                       int patch_size, int downsample_ratio, int max_n_token,
                       pulsar_vision_resize *out) {
    max_n_token -= VISION_COMPRESS_PAD_TO - 1;
    pulsar_vision_grid g = vision_grid_tokens(best_height, best_width, patch_size, downsample_ratio);
    int budget = max_n_token;
    while (g.num_tokens > max_n_token) {
        pulsar_vision_resize r = vision_solve_resize_ratio(height, width, patch_size,
                                                           downsample_ratio, budget);
        if (r.n_llm_h == 0 && r.n_llm_w == 0 && r.best_height == 0 && r.best_width == 0)
            return 0;   /* the reference's assert fired: caller must refuse */
        g.n_llm_h = r.n_llm_h;
        g.n_llm_w = r.n_llm_w;
        g.num_tokens = r.num_tokens;
        best_height = r.best_height;
        best_width = r.best_width;
        budget -= 1;
    }
    out->n_llm_h = g.n_llm_h;
    out->n_llm_w = g.n_llm_w;
    out->best_height = best_height;
    out->best_width = best_width;
    out->num_tokens = g.num_tokens;
    return 1;
}

/* image_processor.build_image_block(): the sentinel TYPES in their final
 * N-layout order, and `perm`, which selects aligner rows into the IMAGE slots.
 * `types_out` receives compress_pad + 1 + rows*row_len + pad_last + 1 entries
 * and `perm_out` receives n_llm_h*n_llm_w.  Returns the types count, or -1 if
 * either buffer is too small. */
int vision_build_image_block(int n_llm_h, int n_llm_w, int start_pos,
                             int *types_out, int types_cap,
                             int *perm_out, int perm_cap) {
    const int compress_pad = VISION_COMPRESS_PAD_TO - 1 - start_pos % VISION_COMPRESS_PAD_TO;
    const int pad_h = n_llm_h % 2;
    const int rows = n_llm_h + pad_h;
    const int row_len = n_llm_w + 1;
    const int total = rows * row_len;
    const int pad_last = (rows / 2) * row_len % 2 * 2;
    const int n_types = compress_pad + 1 + total + pad_last + 1;
    const int n_perm = n_llm_h * n_llm_w;
    if (n_types > types_cap || n_perm > perm_cap) return -1;

    /* types[] before the N-layout reorder:
     *   ([IMAGE] * n_llm_w + [IMAGE_NEW_LINE]) * n_llm_h + [IMAGE_PAD] * (row_len * pad_h)
     * and the (rows, row_len) image-row index map: -1 everywhere except the
     * top-left n_llm_h x n_llm_w block, which counts 0..n_llm_h*n_llm_w-1. */
    int *raw_types = (int *)xmalloc((size_t)total * sizeof(int));
    int *raw_idx = (int *)xmalloc((size_t)total * sizeof(int));
    for (int i = 0; i < total; i++) raw_idx[i] = -1;
    int t = 0;
    for (int h = 0; h < n_llm_h; h++) {
        for (int w = 0; w < n_llm_w; w++) raw_types[t++] = VISION_T_IMAGE;
        raw_types[t++] = VISION_T_IMAGE_NEWLINE;
    }
    for (int i = 0; i < row_len * pad_h; i++) raw_types[t++] = VISION_T_IMAGE_PAD;
    for (int h = 0; h < n_llm_h; h++)
        for (int w = 0; w < n_llm_w; w++) raw_idx[h * row_len + w] = h * n_llm_w + w;

    /* order = arange(total).view(rows/2, 2, row_len).transpose(1,2).reshape(-1),
     * i.e. the 2-row interleave the N-layout uses. */
    int written = 0;
    int perm_n = 0;
    for (int i = 0; i < compress_pad; i++) types_out[written++] = VISION_T_IMAGE_PAD;
    types_out[written++] = VISION_T_IMAGE_START;
    for (int a = 0; a < rows / 2; a++) {
        for (int b = 0; b < row_len; b++) {
            for (int c = 0; c < 2; c++) {
                const int src = a * 2 * row_len + c * row_len + b;
                types_out[written++] = raw_types[src];
                if (raw_idx[src] >= 0) {
                    if (perm_n >= perm_cap) { free(raw_types); free(raw_idx); return -1; }
                    perm_out[perm_n++] = raw_idx[src];
                }
            }
        }
    }
    for (int i = 0; i < pad_last; i++) types_out[written++] = VISION_T_IMAGE_PAD;
    types_out[written++] = VISION_T_IMAGE_END;
    free(raw_types);
    free(raw_idx);
    return written;
}

/* ---------------------------------------------------------------------------
 * The PIXEL half: image_processor.load_image() after the decode.
 *
 * The resampler is a faithful port of Pillow's src/libImaging/Resample.c
 * (BICUBIC, 8bpc, Q22 fixed-point coefficients) plus ImageOps.contain/pad --
 * `ImageOps.pad` scales to fit and centres on a (127,127,127) canvas, and
 * `Image.resize` in the max_wh_ratio branch stretches.  Matching Pillow HERE is
 * the point: the reference (and the vLLM capture) both preprocess with Pillow,
 * so a "close enough" resampler would put every image feature on a slightly
 * different input and there would be nothing to compare against.
 *
 * Everything below is integer or IEEE-deterministic, so this TU is built
 * without -ffast-math (see the Makefile) for the same reason the layout math is.
 * ------------------------------------------------------------------------- */

#define PIL_PRECISION_BITS 22   /* (32 - 8 - 2): 8 bits of result, 2 of overflow */

static double pil_bicubic_filter(double x) {
    const double a = -0.5;
    if (x < 0.0) x = -x;
    if (x < 1.0) return ((a + 2.0) * x - (a + 3.0)) * x * x + 1.0;
    if (x < 2.0) return (((x - 5.0) * x + 8.0) * x - 4.0) * a;
    return 0.0;
}

/* Pillow's clip8(): the lookup table maps (v >> 22) in [-640, 639] to [0,255],
 * negative to 0 and >255 to 255.  Clamping the index keeps the same answers
 * without relying on the filter never overshooting the table. */
static inline uint8_t pil_clip8(int32_t in) {
    int32_t v = in >> PIL_PRECISION_BITS;
    if (v < -640) v = -640;
    if (v > 639) v = 639;
    if (v < 0) return 0;
    if (v > 255) return 255;
    return (uint8_t)v;
}

/* Pillow's precompute_coeffs() for BICUBIC (support 2.0), double coefficients. */
static int pil_precompute_coeffs(int in_size, float in0, float in1, int out_size,
                                 int **bounds_out, double **kk_out) {
    double scale = (double)(in1 - in0) / (double)out_size;
    double filterscale = scale < 1.0 ? 1.0 : scale;
    const double support = 2.0 * filterscale;
    const int ksize = (int)ceil(support) * 2 + 1;
    double *kk = (double *)calloc((size_t)out_size * (size_t)ksize, sizeof(double));
    int *bounds = (int *)malloc((size_t)out_size * 2u * sizeof(int));
    if (!kk || !bounds) { free(kk); free(bounds); return 0; }
    const double inv_filterscale = 1.0 / filterscale;
    for (int xx = 0; xx < out_size; xx++) {
        const double center = (double)in0 + ((double)xx + 0.5) * scale;
        double ww = 0.0;
        int xmin = (int)(center - support + 0.5);
        if (xmin < 0) xmin = 0;
        int xmax = (int)(center + support + 0.5);
        if (xmax > in_size) xmax = in_size;
        xmax -= xmin;
        double *k = &kk[(size_t)xx * (size_t)ksize];
        for (int x = 0; x < xmax; x++) {
            const double w = pil_bicubic_filter(((double)x + xmin - center + 0.5) * inv_filterscale);
            k[x] = w;
            ww += w;
        }
        if (ww != 0.0)
            for (int x = 0; x < xmax; x++) k[x] /= ww;
        bounds[xx * 2 + 0] = xmin;
        bounds[xx * 2 + 1] = xmax;
    }
    *bounds_out = bounds;
    *kk_out = kk;
    return ksize;
}

/* Pillow's normalize_coeffs_8bpc(): double -> Q22, round-half-away-from-zero
 * (add +/-0.5 then truncate toward zero). */
static void pil_normalize_coeffs(int n, const double *pre, int32_t *kk) {
    const double one = (double)(1 << PIL_PRECISION_BITS);
    for (int i = 0; i < n; i++)
        kk[i] = pre[i] < 0.0 ? (int32_t)(-0.5 + pre[i] * one)
                             : (int32_t)(0.5 + pre[i] * one);
}

/* One axis of Pillow's two-pass 8bpc resample for 3 bands.  `vert` selects
 * whether the filter runs down the source rows or across the source columns;
 * the arithmetic (and the 1<<21 rounding seed) is identical either way. */
static void pil_resample_axis(uint8_t *dst, int dst_w, int dst_h,
                              const uint8_t *src, int src_w, int src_h,
                              int ksize, const int *bounds, const int32_t *kk,
                              int vert) {
    (void)src_h;
    for (int y = 0; y < dst_h; y++) {
        uint8_t *line_out = dst + (size_t)y * (size_t)dst_w * 3u;
        const int ymin = vert ? bounds[y * 2 + 0] : 0;
        const int ymax = vert ? bounds[y * 2 + 1] : 0;
        const int32_t *krow = vert ? &kk[(size_t)y * (size_t)ksize] : NULL;
        for (int xx = 0; xx < dst_w; xx++) {
            const int xmin = vert ? 0 : bounds[xx * 2 + 0];
            const int xmax = vert ? 0 : bounds[xx * 2 + 1];
            const int32_t *k = vert ? krow : &kk[(size_t)xx * (size_t)ksize];
            int32_t s0 = 1 << (PIL_PRECISION_BITS - 1);
            int32_t s1 = s0, s2 = s0;
            if (vert) {
                for (int y2 = 0; y2 < ymax; y2++) {
                    const uint8_t *p = src + ((size_t)(y2 + ymin) * (size_t)src_w + (size_t)xx) * 3u;
                    s0 += p[0] * k[y2];
                    s1 += p[1] * k[y2];
                    s2 += p[2] * k[y2];
                }
            } else {
                const uint8_t *row = src + (size_t)y * (size_t)src_w * 3u;
                for (int x2 = 0; x2 < xmax; x2++) {
                    const uint8_t *p = row + ((size_t)(x2 + xmin)) * 3u;
                    s0 += p[0] * k[x2];
                    s1 += p[1] * k[x2];
                    s2 += p[2] * k[x2];
                }
            }
            line_out[(size_t)xx * 3u + 0] = pil_clip8(s0);
            line_out[(size_t)xx * 3u + 1] = pil_clip8(s1);
            line_out[(size_t)xx * 3u + 2] = pil_clip8(s2);
        }
    }
}

/* ImagingResample() for one dimension pair: horizontal first, then vertical,
 * skipping a pass whose size is unchanged (Pillow's need_horizontal/vertical).
 * `box` is always the whole source, which is what Image.resize uses. */
static uint8_t *pil_resize_rgb(const uint8_t *src, int src_w, int src_h,
                               int dst_w, int dst_h) {
    uint8_t *cur = (uint8_t *)src;
    uint8_t *alloc1 = NULL, *alloc2 = NULL;
    int cur_w = src_w, cur_h = src_h;

    if (dst_w != src_w) {
        int *bounds = NULL; double *pre = NULL;
        int ksize = pil_precompute_coeffs(src_w, 0.0f, (float)src_w, dst_w, &bounds, &pre);
        if (!ksize) return NULL;
        int32_t *kk = (int32_t *)malloc((size_t)dst_w * (size_t)ksize * sizeof(int32_t));
        alloc1 = (uint8_t *)malloc((size_t)dst_w * (size_t)cur_h * 3u);
        if (!kk || !alloc1) { free(kk); free(bounds); free(pre); free(alloc1); return NULL; }
        pil_normalize_coeffs(dst_w * ksize, pre, kk);
        pil_resample_axis(alloc1, dst_w, cur_h, cur, cur_w, cur_h, ksize, bounds, kk, 0);
        free(kk); free(bounds); free(pre);
        cur = alloc1; cur_w = dst_w;
    }
    if (dst_h != src_h) {
        int *bounds = NULL; double *pre = NULL;
        int ksize = pil_precompute_coeffs(src_h, 0.0f, (float)src_h, dst_h, &bounds, &pre);
        if (!ksize) { free(alloc1); return NULL; }
        int32_t *kk = (int32_t *)malloc((size_t)dst_h * (size_t)ksize * sizeof(int32_t));
        alloc2 = (uint8_t *)malloc((size_t)cur_w * (size_t)dst_h * 3u);
        if (!kk || !alloc2) { free(kk); free(bounds); free(pre); free(alloc1); free(alloc2); return NULL; }
        pil_normalize_coeffs(dst_h * ksize, pre, kk);
        pil_resample_axis(alloc2, cur_w, dst_h, cur, cur_w, cur_h, ksize, bounds, kk, 1);
        free(kk); free(bounds); free(pre);
        free(alloc1);   /* the horizontal pass's temp, when there was one */
        cur = alloc2;
    }
    if (cur == src) {   /* nothing changed: Pillow copies */
        size_t n = (size_t)src_w * (size_t)src_h * 3u;
        uint8_t *copy = (uint8_t *)malloc(n);
        if (copy) memcpy(copy, src, n);
        return copy;
    }
    return cur;
}

/* Python's round(): ties-to-even, which is what ImageOps.pad uses for the paste
 * offset and ImageOps.contain for the contained size. */
static int py_round(double v) {
    double r = nearbyint(v);   /* default FE_TONEAREST == half to even */
    return (int)r;
}

/* float32 -> bfloat16, round-to-nearest-even, as torch's .to(bfloat16) does. */
static uint16_t f32_to_bf16_bits(float f) {
    uint32_t u;
    memcpy(&u, &f, sizeof u);
    const uint32_t lsb = (u >> 16) & 1u;
    u += 0x7fffu + lsb;
    return (uint16_t)(u >> 16);
}

int vision_preprocess_rgb(const uint8_t *rgb, int width, int height,
                          const pulsar_vision_args *args,
                          uint16_t *patch_out, size_t patch_cap,
                          pulsar_vision_image *out) {
    const int p = args->patch_size;
    const int dr = args->downsample_ratio;
    const float max_wh = args->max_wh_ratio;

    /* load_image(): the max_wh_ratio clamp and the min_pixels upscale act on the
     * VARIABLES only; the decoded image is untouched. */
    int vw = width, vh = height;
    if (max_wh > 0.0f && (float)vw > (float)vh * max_wh)
        vw = (int)((float)vh * max_wh);
    if (vw * vh > 0 && vw * vh < args->min_pixels) {
        const double ratio = sqrt((double)args->min_pixels / ((double)vw * (double)vh));
        vw = (int)((double)vw * ratio);
        vh = (int)((double)vh * ratio);
    }
    int best_w = (int)(((vw + p - 1) / p) * p);
    int best_h = (int)(((vh + p - 1) / p) * p);
    pulsar_vision_resize sr;
    if (!vision_safe_resize(vh, vw, best_h, best_w, p, dr, args->max_n_token, &sr))
        return 0;
    best_h = sr.best_height;
    best_w = sr.best_width;
    const int n_vit_h = best_h / p;
    const int n_vit_w = best_w / p;

    /* The resize/pad branch, then ImageOps.pad's contain + centred paste. */
    uint8_t *canvas = NULL;
    if (max_wh > 0.0f && (float)width >= max_wh * (float)height) {
        canvas = pil_resize_rgb(rgb, width, height, best_w, best_h);
    } else {
        const double im_ratio = (double)width / (double)height;
        const double dest_ratio = (double)best_w / (double)best_h;
        int cw = best_w, ch = best_h;
        if (im_ratio != dest_ratio) {
            if (im_ratio > dest_ratio) {
                const int nh = py_round((double)height / (double)width * (double)best_w);
                if (nh != best_h) ch = nh;
            } else {
                const int nw = py_round((double)width / (double)height * (double)best_h);
                if (nw != best_w) cw = nw;
            }
        }
        uint8_t *resized = pil_resize_rgb(rgb, width, height, cw, ch);
        if (!resized) return 0;
        if (cw == best_w && ch == best_h) {
            canvas = resized;
        } else {
            canvas = (uint8_t *)malloc((size_t)best_w * (size_t)best_h * 3u);
            if (!canvas) { free(resized); return 0; }
            memset(canvas, 127, (size_t)best_w * (size_t)best_h * 3u);
            int ox = 0, oy = 0;
            if (cw != best_w) ox = py_round((double)(best_w - cw) * 0.5);
            else              oy = py_round((double)(best_h - ch) * 0.5);
            for (int y = 0; y < ch; y++)
                memcpy(canvas + ((size_t)(y + oy) * (size_t)best_w + (size_t)ox) * 3u,
                       resized + (size_t)y * (size_t)cw * 3u, (size_t)cw * 3u);
            free(resized);
        }
    }
    if (!canvas) return 0;

    /* x = float32(rgb)/255; x = (x-0.5)/0.5; to bf16; then patchify:
     * reshape(3, n_vit_h, p, n_vit_w, p).permute(1,3,0,2,4). */
    const size_t n_patch = (size_t)n_vit_h * (size_t)n_vit_w;
    const size_t per_patch = (size_t)3 * (size_t)p * (size_t)p;
    if (n_patch * per_patch > patch_cap) { free(canvas); return 0; }
    for (int i = 0; i < n_vit_h; i++) {
        for (int j = 0; j < n_vit_w; j++) {
            uint16_t *dst = patch_out + ((size_t)i * (size_t)n_vit_w + (size_t)j) * per_patch;
            for (int c = 0; c < 3; c++) {
                for (int py = 0; py < p; py++) {
                    for (int px = 0; px < p; px++) {
                        const uint8_t byte = canvas[((size_t)(i * p + py) * (size_t)best_w +
                                                     (size_t)(j * p + px)) * 3u + (size_t)c];
                        const float x = (float)byte / 255.0f;
                        const float n = (x - 0.5f) / 0.5f;
                        dst[((size_t)c * (size_t)p + (size_t)py) * (size_t)p + (size_t)px] =
                            f32_to_bf16_bits(n);
                    }
                }
            }
        }
    }
    free(canvas);
    out->n_vit_h = n_vit_h;
    out->n_vit_w = n_vit_w;
    out->n_llm_h = sr.n_llm_h;
    out->n_llm_w = sr.n_llm_w;
    out->best_width = best_w;
    out->best_height = best_h;
    return 1;
}

/* ---------------------------------------------------------------------------
 * The CODEC.
 *
 * PNG through libpng's simplified API (PNG_FORMAT_RGB: every colour type, bit
 * depth and interlace mode reduced to 8-bit RGB, alpha dropped -- exactly what
 * Pillow's .convert("RGB") yields).  JPEG through libjpeg-turbo with Pillow's
 * settings, which are libjpeg's DEFAULTS: Pillow only touches dct_method and
 * do_fancy_upsampling in draft mode (see libImaging/JpegDecode.c), so JDCT_ISLOW
 * + fancy upsampling + block smoothing + JCS_RGB output is what it gets and what
 * we ask for.
 *
 * CMYK/YCCK JPEG is REFUSED rather than converted: Pillow keeps those in CMYK
 * and its own .convert("RGB") is a different transform from libjpeg's, so a
 * silent agreement would be luck.  Anything that is not PNG or JPEG is refused
 * by the dispatcher -- the caller fails loudly, it does not guess.
 * ------------------------------------------------------------------------- */

static int vision_decode_png(const uint8_t *bytes, size_t len,
                             uint8_t **rgb_out, int *w_out, int *h_out) {
    png_image image;
    memset(&image, 0, sizeof image);
    image.version = PNG_IMAGE_VERSION;
    if (!png_image_begin_read_from_memory(&image, bytes, len)) return 0;
    /* Decode to RGBA and drop the alpha HERE rather than asking libpng for
     * PNG_FORMAT_RGB: given an alpha source and a background of NULL, libpng
     * composites (measured: an alpha=200 pixel came back as 69 where the source
     * was 0), while Pillow's .convert("RGB") discards the alpha outright.  The
     * gate caught exactly that on an RGBA PNG. */
    image.format = PNG_FORMAT_RGBA;
    if (image.width == 0 || image.height == 0 ||
        image.width > (png_uint_32)INT32_MAX || image.height > (png_uint_32)INT32_MAX) {
        png_image_free(&image);
        return 0;
    }
    const size_t sz = PNG_IMAGE_SIZE(image);
    uint8_t *rgba = (uint8_t *)malloc(sz);
    if (!rgba) { png_image_free(&image); return 0; }
    if (!png_image_finish_read(&image, NULL, rgba, 0, NULL)) {
        free(rgba);
        png_image_free(&image);
        return 0;
    }
    const size_t npix = (size_t)image.width * (size_t)image.height;
    uint8_t *buf = (uint8_t *)malloc(npix * 3u);
    if (!buf) { free(rgba); png_image_free(&image); return 0; }
    for (size_t i = 0; i < npix; i++) {
        buf[i * 3 + 0] = rgba[i * 4 + 0];
        buf[i * 3 + 1] = rgba[i * 4 + 1];
        buf[i * 3 + 2] = rgba[i * 4 + 2];
    }
    free(rgba);
    *w_out = (int)image.width;
    *h_out = (int)image.height;
    png_image_free(&image);
    *rgb_out = buf;
    return 1;
}

struct vision_jpeg_error {
    struct jpeg_error_mgr pub;
    jmp_buf jb;
};

static void vision_jpeg_error_exit(j_common_ptr cinfo) {
    struct vision_jpeg_error *e = (struct vision_jpeg_error *)cinfo->err;
    longjmp(e->jb, 1);
}
static void vision_jpeg_output_message(j_common_ptr cinfo) { (void)cinfo; }

static int vision_decode_jpeg(const uint8_t *bytes, size_t len,
                              uint8_t **rgb_out, int *w_out, int *h_out) {
    struct jpeg_decompress_struct cinfo;
    struct vision_jpeg_error jerr;
    memset(&cinfo, 0, sizeof cinfo);   /* so the longjmp path's destroy is a no-op */
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = vision_jpeg_error_exit;
    jerr.pub.output_message = vision_jpeg_output_message;
    if (setjmp(jerr.jb)) {
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }
    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, bytes, (unsigned long)len);
    if (jpeg_read_header(&cinfo, TRUE) != JPEG_HEADER_OK) {
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }
    if (cinfo.jpeg_color_space == JCS_CMYK || cinfo.jpeg_color_space == JCS_YCCK) {
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }
    cinfo.out_color_space = JCS_RGB;
    if (!jpeg_start_decompress(&cinfo)) {
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }
    const int cw = (int)cinfo.output_width, ch = (int)cinfo.output_height;
    if (cinfo.output_components != 3 || cw <= 0 || ch <= 0 ||
        (size_t)cw > SIZE_MAX / 3u / (size_t)ch) {
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }
    uint8_t *buf = (uint8_t *)malloc((size_t)cw * (size_t)ch * 3u);
    if (!buf) { jpeg_destroy_decompress(&cinfo); return 0; }
    while (cinfo.output_scanline < cinfo.output_height) {
        uint8_t *row = buf + (size_t)cinfo.output_scanline * (size_t)cw * 3u;
        JSAMPROW rows[1] = { row };
        if (jpeg_read_scanlines(&cinfo, rows, 1) != 1) {
            free(buf);
            jpeg_destroy_decompress(&cinfo);
            return 0;
        }
    }
    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
    *w_out = cw;
    *h_out = ch;
    *rgb_out = buf;
    return 1;
}

/* Formats the server accepts today: PNG and JPEG.  A GIF/WebP/... payload is
 * refused by name rather than mis-parsed. */
int vision_decode_rgb(const uint8_t *bytes, size_t len,
                      uint8_t **rgb_out, int *w_out, int *h_out) {
    if (!bytes || len < 8) return 0;
    static const uint8_t png_sig[8] = { 0x89, 'P', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a };
    if (!memcmp(bytes, png_sig, 8)) return vision_decode_png(bytes, len, rgb_out, w_out, h_out);
    if (bytes[0] == 0xFF && bytes[1] == 0xD8) return vision_decode_jpeg(bytes, len, rgb_out, w_out, h_out);
    return 0;
}

/* Flatten the engine's bound tower into the CUDA-facing offset contract and run
 * the forward.  This is the ONLY place the two sides meet: the kernels cannot
 * see pulsar_vision_weights (see pulsar_gpu.h). */
int vision_forward(const pulsar_vision_weights *w, const pulsar_model *m,
                   const uint16_t *patches, int n_h, int n_w,
                   uint16_t *out, int out_cap, int *out_rows,
                   uint16_t *dbg, uint32_t dbg_blocks) {
    if (!w || !m || w->n_layers != PULSAR_VISION_LAYERS) return 0;
    pulsar_vision_offsets o;
    memset(&o, 0, sizeof o);
    o.n_layers = w->n_layers;
    o.text_dim = (uint32_t)PULSAR_N_EMBD;
    o.patch_proj = w->patch_proj->abs_offset;
    o.patch_bias = w->patch_bias->abs_offset;
    o.norm = w->norm->abs_offset;
    o.aligner_w1 = w->aligner_w1->abs_offset;
    o.aligner_b1 = w->aligner_b1->abs_offset;
    o.aligner_w2 = w->aligner_w2->abs_offset;
    o.aligner_b2 = w->aligner_b2->abs_offset;
    for (uint32_t i = 0; i < w->n_layers; i++) {
        o.block[i].norm1     = w->block[i].norm1->abs_offset;
        o.block[i].wqkv      = w->block[i].wqkv->abs_offset;
        o.block[i].wqkv_bias = w->block[i].wqkv_bias->abs_offset;
        o.block[i].wo        = w->block[i].wo->abs_offset;
        o.block[i].wo_bias   = w->block[i].wo_bias->abs_offset;
        o.block[i].norm2     = w->block[i].norm2->abs_offset;
        o.block[i].w1        = w->block[i].w1->abs_offset;
        o.block[i].w2        = w->block[i].w2->abs_offset;
    }
    return pulsar_cuda_vision_forward(&o, m->map, m->size, patches, n_h, n_w,
                                      out, out_cap, out_rows, dbg, dbg_blocks);
}


/* The per-image input path end to end: decode -> preprocess -> sentinel span.
 * This is the reference's prepare_vl_inputs minus the prompt tokenisation (which
 * the renderer owns): load_image -> build_image_block(len(tokens)) -> ids are
 * vocab_size + type.  The pieces were each gated separately; this composes them,
 * which is what the server will actually call. */
int vision_prepare_image(const uint8_t *bytes, size_t len, const pulsar_vision_args *args,
                         int start_pos, int vocab_size, pulsar_vision_prepared *out) {
    memset(out, 0, sizeof *out);
    uint8_t *rgb = NULL;
    int w = 0, h = 0;
    if (!vision_decode_rgb(bytes, len, &rgb, &w, &h)) return 0;

    pulsar_vision_image img;
    const size_t cap = (size_t)w * (size_t)h;   /* an upper bound on patch elements/3 */
    uint16_t *patches = (uint16_t *)malloc(cap * 3u * sizeof(uint16_t));
    if (!patches) { free(rgb); return 0; }
    const size_t patch_cap = cap * 3u;
    if (!vision_preprocess_rgb(rgb, w, h, args, patches, patch_cap, &img)) {
        free(patches);
        free(rgb);
        return 0;
    }
    free(rgb);

    const int p = args->patch_size;
    const int n_patches = img.n_vit_h * img.n_vit_w;
    const size_t used = (size_t)n_patches * 3u * (size_t)p * (size_t)p;

    int32_t *ids = (int32_t *)malloc((size_t)img.n_llm_h * (size_t)(img.n_llm_w + 1) * 4u * sizeof(int32_t) + 64u);
    int32_t *types = (int32_t *)malloc((size_t)img.n_llm_h * (size_t)(img.n_llm_w + 1) * 4u * sizeof(int32_t) + 64u);
    int32_t *perm = (int32_t *)malloc((size_t)n_patches * sizeof(int32_t) + 1u);
    int *raw_types = NULL;
    if (!ids || !types || !perm) goto fail_tmp;
    {
        const int cap_ids = (int)((size_t)img.n_llm_h * (size_t)(img.n_llm_w + 1) * 4u + 64u);
        raw_types = (int *)malloc((size_t)cap_ids * sizeof(int));
        if (!raw_types) goto fail_tmp;
        const int n_types = vision_build_image_block(img.n_llm_h, img.n_llm_w, start_pos,
                                                     raw_types, cap_ids, perm, n_patches);
        if (n_types <= 0) goto fail_tmp;
        for (int i = 0; i < n_types; i++) {
            types[i] = raw_types[i];
            ids[i] = vocab_size + raw_types[i];
        }
        out->span_len = n_types;
        out->n_perm = n_patches;
    }
    free(raw_types);
    out->patches = patches;
    out->span_ids = ids;
    out->span_types = types;
    out->perm = perm;
    out->n_patches = n_patches;
    out->n_vit_h = img.n_vit_h;
    out->n_vit_w = img.n_vit_w;
    out->n_llm_h = img.n_llm_h;
    out->n_llm_w = img.n_llm_w;
    (void)used;
    return 1;

fail_tmp:
    free(raw_types);
    free(ids);
    free(types);
    free(perm);
    free(patches);
    return 0;
}

void vision_prepared_free(pulsar_vision_prepared *p) {
    if (!p) return;
    free(p->patches);
    free(p->span_ids);
    free(p->span_types);
    free(p->perm);
    memset(p, 0, sizeof *p);
}
